Update styling
cennznet/app-identity pull request #7
Opened 2022-03-18 03:01 UTC by aidan-starke

## Description

- Update styling & add CENNZnet wallet

## Details

#### Changes

 - add `DiscordHandler` and `TwitterHandler` buttons
 - allow user to connect CENNZ wallet and select account
 - add details about the Identity module

2022-03-20 21:57 UTC, ken-centrality requested changes
Code looks good, Interface looks good, one thing I would change is the Discord and Twitter buttons should not appear until you connect to CENNZnet, not the other way around

2022-03-20 22:25 UTC, aidan-starke commented
> Code looks good, Interface looks good, one thing I would change is the Discord and Twitter buttons should not appear until you connect to CENNZnet, not the other way around

As the auth process involves a redirect, the CENNZnet session would be wiped each time they come back

2022-03-21 21:41 UTC, ken-centrality approved these changes
One more thing from me is, do we want to allow user to pick however they want to connect, or would it be simpler to force them to connect the CENNZnet first, then provide them options between Twitter / Discord after.

2022-03-21 21:41 UTC, ken-centrality commented on packages/next-app/libs/hooks/useLocalStorage.ts
> +	const setValue = (value: T | ((val: T) => T)) => {
nice custom hook! i wonder if it's better to use `useEffect` to handle the initial `setStoredValue` part. As I can see here you have to do a bit of guarding due to server side rendering.

Server side rendering will never touch `useEffect`, so you can safely use `window` object in there.

2022-03-22 00:48 UTC, aidan-starke commented
> One more thing from me is, do we want to allow user to pick however they want to connect, or would it be simpler to force them to connect the CENNZnet first, then provide them options between Twitter / Discord after.

I'm happy with the way it is now, but if we want to we could lose the twitter/discord buttons, and once they have connected CENNZnet they can use the same button to popup a sign in page. from that sign in page they could select Twitter / Discord.

I am having an issue with the sign-in popup though, looking in to it now
<img width="383" alt="Screen Shot 2022-03-22 at 1 47 57 PM" src="https://user-images.githubusercontent.com/52016903/159385842-2c546d88-5dfc-4a49-862d-6c7b2e5bf9f1.png">

2022-03-22 01:54 UTC, merged